services:
  - type: web
    name: crypto-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard_app.py

cronJobs:
  - name: tier1-scan
    schedule: "*/45 8-21 * * *"
    command: python scanner_core.py
